name: TGOPS Deploy
description: Deploy a project using TGOPS
inputs:
  env:
    description: Deploy environment
    required: true
    type: string
  tgops-token:
    description: Secret token with permission to access the TGOPS repository artifacts
    required: true
    type: string
  deploy-token:
    description: Kubernetes service account token
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Download tgops executable
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.tgops-token }}
      run: |
        run_id=$(gh run list \
          --repo tweedegolf/tgops \
          --workflow build.yml \
          --status success \
          --limit 1 \
          --json databaseId \
          --jq '.[0].databaseId')
        gh run download "$run_id" --repo tweedegolf/tgops --name tgops

    - name: Run tgops deploy
      run: chmod +x ./tgops && ./tgops deploy --force
      shell: bash
      env:
        ENV: ${{inputs.env}}
        DEPLOY_TOKEN: ${{inputs.deploy-token}}
